export const SPLASH_TEXTS = [
  "Also try Desperados!",
  "Hoppy endings guaranteed!",
  "Ale be back!",
  "Brewing memories!",
  "Cheers to good beers!",
  "Lager than life!",
  "IPA lot when I drink!",
  "Craft beer, craft life!",
  "Wheat dreams are made of!",
  "Stout and proud!",
  "Porter? I hardly know her!",
  "Pilsner perfect!",
  "Ale's well that ends well!",
  "Beer me up, Scotty!",
  "In hops we trust!",
  "Barrel-aged to perfection!",
  "Sour power!",
  "Belgian strong, always!",
  "Trappist or treat!",
  "Saison the day!",
  "Kolsch and collected!",
  "Wit happens!",
  "Bock to basics!",
  "Dunkel side of beer!",
  "Märzen madness!",
  "Rauchbier dreams!",
  "Gose wild!",
  "Lambic love!",
  "Gueuze or lose!",
  "Flanders red, well fed!",
  "Dubbel trouble!",
  "Tripel threat!",
  "Quadrupel the fun!",
  "Ale yeah!",
  "Brew-tiful memories!",
  "Cascadian dark magic!",
  "Session all day!",
  "Imperial strength!",
  "Barleywine fine!",
  "Malt made in heaven!",
  "Hazy but not lazy!",
  "NEIPA vibes!",
  "West Coast beast!",
  "East Coast yeast!",
  "Dank and dandy!",
  "Mosaic magic!",
  "Citra citrus!",
  "Galaxy far, far away!",
  "Simcoe simplicity!",
  "Amarillo armadillo!",
  "El Dorado dreams!",
  "Centennial celebration!",
  "Cascade waterfall!",
  "Now with 100% more hops!",
  "Contains gluten!",
  "Fermented with love!",
  "Yeast mode activated!",
  "Carbonated happiness!",
  "ABV? More like YAY!",
  "Made from grain!",
  "Not a wine!",
  "Better than water!",
  "Pairs with everything!",
  "Food is overrated!",
  "Liquid bread!",
  "Ancient technology!",
  "Since 4000 BC!",
  "Mesopotamian approved!",
  "Monks approved!",
  "Reinheitsgebot compliant!",
  "Or maybe not!",
  "Contains alcohol!",
  "Must be 21+!",
  "Drink responsibly!",
  "Or irresponsibly!",
  "But mostly responsibly!",
  "Prost!",
  "Salud!",
  "Santé!",
  "Skål!",
  "Na zdraví!",
  "Kampai!",
  "Gan bei!",
  "Cheers, mate!",
  "Bottoms up!",
  "To your health!",
  "L'chaim!",
  "Sláinte!",
  "Živeli!",
  "Noroc!",
  "Egészségedre!",
  "Rate it!",
  "Log it!",
  "Drink it!",
  "Share it!",
  "Review it!",
  "Collect them all!",
  "Gotta drink 'em all!",
  "Achievement unlocked!",
  "Level up your palate!",
  "XP: +100 taste!",
  "Quest: Try 100 beers!",
  "Rare beer spotted!",
  "Legendary brew!",
  "Epic flavor!",
  "Common but delicious!",
  "Craft brewery nearby!",
  "Beer festival ahead!",
  "Tap takeover!",
  "Fresh batch!",
  "Seasonal special!",
  "Limited edition!",
  "Small batch magic!",
  "Barrel #42!",
  "Bottled by hand!",
  "Canned for freshness!",
  "Draft perfection!",
  "Nitro smooth!",
  "Widget inside!",
  "Swing top!",
  "Cork and cage!",
  "440ml of joy!",
  "16oz of happiness!",
  "Pint-sized fun!",
  "Tallboy time!",
  "Bomber bottle!",
  "Magnum size!",
  "Growler fresh!",
  "Crowler sealed!",
  "Firkin Friday!",
  "Cask conditioned!",
  "No adjuncts!",
  "All natural!",
  "Organic hops!",
  "Local malt!",
  "Mountain water!",
  "Spring fresh!",
  "Glacier pure!",
  "Wild yeast!",
  "Spontaneous fermentation!",
  "Coolship cooled!",
  "Open fermentation!",
  "Wood aged!",
  "Bourbon barrel!",
  "Wine barrel!",
  "Rum barrel!",
  "Tequila barrel!",
  "Whiskey soaked!",
  "Oak influenced!",
  "Brett funky!",
  "Lacto sour!",
  "Pedio complexity!",
  "Mixed culture!",
  "House culture!",
  "Belgian yeast!",
  "German yeast!",
  "English yeast!",
  "American yeast!",
  "Kveik quick!",
  "Dry hopped!",
  "Wet hopped!",
  "Fresh hopped!",
  "Lupulin powder!",
  "Cryo hops!",
  "Double dry hopped!",
  "Triple dry hopped!",
  "Hop burst!",
  "Late addition!",
  "Whirlpool magic!",
  "First wort hopped!",
  "Continuous hopping!",
  "Fruit forward!",
  "Vanilla notes!",
  "Coffee infused!",
  "Chocolate malt!",
  "Caramel sweetness!",
  "Roasted character!",
  "Toasted perfection!",
  "Smoked malt!",
  "Peat smoked!",
  "Honeyed goodness!",
  "Spiced up!",
  "Citrus zest!",
  "Tropical vibes!",
  "Stone fruit!",
  "Berry notes!",
  "Floral aroma!",
  "Earthy undertones!",
  "Piney goodness!",
  "Dank resin!",
  "Juicy IPA!",
  "Crisp and clean!",
  "Smooth finish!",
  "Dry finish!",
  "Bitter sweet!",
  "Balanced beauty!",
  "Malt forward!",
  "Hop forward!",
  "Yeast character!",
  "Complex layers!",
  "Simple pleasure!",
  "Crushable!",
  "Sessionable!",
  "Sipper not chupper!",
  "Share with friends!",
  "Or keep it all!",
  "Mostly keep it!",
  "Cellar worthy!",
  "Drink fresh!",
  "Ages well!",
  "Best before never!",
  "Vintage: This year!",
  "Rare release!",
  "Annual tradition!",
  "Winter warmer!",
  "Summer refresher!",
  "Spring awakening!",
  "Fall harvest!",
  "Oktoberfest ready!",
  "Christmas cheer!",
  "New Year's toast!",
  "Birthday beer!",
  "Celebration time!",
  "Weekend warrior!",
  "Monday medicine!",
  "Friday feeling!",
  "Thirsty Thursday!",
  "Taco Tuesday!",
  "Any day beer!",
  "Morning beer!",
  "Wait, really?",
  "Noon balloon!",
  "Afternoon delight!",
  "Evening sipping!",
  "Late night cap!",
  "Midnight snack!",
  "3am regret!",
  "Just kidding!",
  "Hydrate too!",
  "Water is important!",
  "Seriously, drink water!",
  "Designated driver available?",
  "Uber exists!",
  "Walk home!",
  "Stay safe!",
  "Know your limits!",
  "Quality over quantity!",
  "Unless quantity!",
  "But mostly quality!",
  "Support local!",
  "Visit the brewery!",
  "Meet the brewer!",
  "Tour the facility!",
  "See the tanks!",
  "Smell the mash!",
  "Hear the bubbles!",
  "Taste the wort!",
  "Feel the grain!",
  "Experience beer!",
  "Join the club!",
  "Beer of the month!",
  "Mug club member!",
  "VIP tasting!",
  "Back room access!",
  "First dibs!",
  "Early release!",
  "Member exclusive!",
  "Founders edition!",
  "Anniversary batch!",
  "Collaboration brew!",
  "Cross-brewery magic!",
  "International team!",
  "Local love!",
  "Neighborhood gem!",
  "Hidden treasure!",
  "Well-known classic!",
  "Underrated!",
  "Overrated!",
  "Properly rated!",
  "Hype train!",
  "Worth the wait!",
  "Instant classic!",
  "Time-tested!",
  "New favorite!",
  "Old reliable!",
  "Try something new!",
  "Stick with what works!",
  "Branch out!",
  "Explore styles!",
  "Rate honestly!",
  "Detailed notes!",
  "Quick review!",
  "Long description!",
  "Emoji allowed!",
  "Words matter!",
  "Photos encouraged!",
  "Share your thoughts!",
  "Compare with friends!",
  "Build your database!",
  "Track your journey!",
  "Remember the moment!",
  "Capture the flavor!",
  "Document the experience!",
  "Create memories!",
  "Cheers to brewing!",
];
